on:
  push:
    branches:
      - master
    paths-ignore:
      - "dist/**"
      - "README.md" 
name: Template
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: k14s/image@sha256:e480fe67da1bd504a4a119bcd29fb20df6453e826889334b26f90e9a20112385
    steps:
    - uses: actions/checkout@master
    - name: Generate Kubernetes configs using YTT 
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_BUILDKIT: "1"
      run: |
        wget -qO- https://get.docker.com/ | sh
        docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        ytt -f snykit.yaml -f values.yaml | kbld -f - > dist/snykit.yaml
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: master
        github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        commit_author: "gareth@morethanseven.net"
        commit_message: Generated Kubernetes configuration from YTT source
